# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='太原市', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='山西省', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='山西大学', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=256),
        ),
    ]
