# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190107_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('保密', '保密')], default='男性', max_length=4),
        ),
    ]
