# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20190107_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('context', models.TextField()),
                ('image1', models.CharField(max_length=256, null=True)),
                ('image2', models.CharField(max_length=256, null=True)),
                ('image3', models.CharField(max_length=256, null=True)),
                ('userName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'confess',
            },
        ),
    ]
