# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_confess'),
    ]

    operations = [
        migrations.AddField(
            model_name='confess',
            name='state',
            field=models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('未通过', '未通过')], default='待审核', max_length=50),
        ),
    ]
