# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_comment_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 21, 16, 58, 29, 238225)),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 21, 16, 58, 29, 238225)),
        ),
    ]
