# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_auto_20190121_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confess',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='confess',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='confess',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='confess',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
