# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_auto_20190121_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confess',
            name='context',
            field=models.TextField(default='', null=True, verbose_name='发表内容'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='images',
            field=models.TextField(default='', verbose_name='发表配图'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1548084137', max_length=256, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='state',
            field=models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('未通过', '未通过')], default='待审核', max_length=50, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='userID',
            field=models.IntegerField(default=1, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='confess',
            name='userName',
            field=models.CharField(default='表白墙', max_length=30, verbose_name='用户昵称'),
        ),
    ]
