# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0018_auto_20190320_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('caredUserId', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'care',
            },
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1553076383', max_length=256, verbose_name='发布时间'),
        ),
    ]
