# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_auto_20190320_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('messageType', models.CharField(max_length=10)),
                ('messageState', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1553478825', max_length=256, verbose_name='发布时间'),
        ),
    ]
