# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_auto_20190325_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1553479761', max_length=256, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='messageState',
            field=models.CharField(default='未读', max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='messageType',
            field=models.CharField(default='系统', max_length=10),
        ),
    ]
