# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_auto_20190325_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='confess',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1554870287', max_length=256, verbose_name='发布时间'),
        ),
    ]
