# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_auto_20190410_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confess',
            old_name='like',
            new_name='collectCount',
        ),
        migrations.AddField(
            model_name='confess',
            name='commentCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confess',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confess',
            name='release_time',
            field=models.CharField(default='1554960322', max_length=256, verbose_name='发布时间'),
        ),
    ]
